zhekou:
  location:
    - Adelaide
    - Brisbane
    - Canberra
    - Gold Coast
    - Melbourne
    - Newcastle
    - Perth
    - Sydney
    - Wollongong
  category:
    - Food
    - Event
    - Travel
    - Goods